library(R6)
library(TDA)
library(myfs)
library(rgl)
library(phacm)
library(pracma)
library(deldir)
library(ggplot2)
library(plyr)
library(reshape2)
library(ggmap)
library(tidyverse)
library(interpo3d)
library(usephacm)
#library(gtm)
library(plotly)
library(devtools)
library(magrittr)
library(tagcloud)
library(colorRamps)
library(TDAstats)
library(abind)
library(parallel)
# library(ider)
library(RColorBrewer)

#source('~/R/interpolation_test/interpo_func.R', encoding = 'UTF-8')
# source('~/R/interpolation_test/interpo_func_2.R', encoding = 'UTF-8')
# source('~/R/interpolation_test/interpo_func.R', encoding = 'UTF-8')
# source('~/R/p_reduce/reduce_func.R', encoding = 'UTF-8')
# source('~/R/interpolation_test/reduce_func2.R', encoding = 'UTF-8')

source('~/R/ph_jikken2/new-okayasu/BootstrapHomology-mk1.R', encoding = 'UTF-8')
source('~/R/ph_jikken2/new-okayasu/m1_main-mk1.R', encoding = 'UTF-8')
source('~/R/distance_ph/R6trial.R', encoding = 'UTF-8')
source('~/R/distance_ph/auto_estimate_betti_functions.R', encoding = 'UTF-8')
source('~/R/distance_ph/dist_ch_func.R', encoding = 'UTF-8')
source('~/R/distance_ph/data_generate_func.R', encoding = 'UTF-8')
source('~/R/distance_ph/smooth_landscape_func.R', encoding = 'UTF-8')
